name: Integration Test

on:
  push:
    branches: [main, devs]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [main]
    paths:
      - 'web-app/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./web-app
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with: 
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm test

  build:
    
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./web-app
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with: 
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  coverage:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./web-app
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm test -- --coverage
      - uses:  actions/upload-artifact@v3
        name: Active Coverage Report
        with:
          name: coverage-report
          path: coverage
      